// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific
// target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonIDs(WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.String[],System.Int32,System.Boolean)~System.Threading.Tasks.Task{System.Int32[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.DownloadAddonAsync(WorkshopUtils.WorkshopAddon,System.String)~System.Threading.Tasks.Task" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonIDsAsync(WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.String[],System.Int32)~System.Threading.Tasks.Task{System.Int32[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.DownloadAddonDataAsync(WorkshopUtils.WorkshopAddon)~System.Threading.Tasks.Task{System.Byte[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.DownloadAddonFileAsync(WorkshopUtils.WorkshopAddon,System.String)~System.Threading.Tasks.Task" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonsAsync(System.String,WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.Int32)~System.Threading.Tasks.Task{WorkshopUtils.WorkshopAddon[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.ChoiceForm.Button1_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0061:Asynchronous method can be terminated with the 'Async' keyword.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.ChoiceForm.Button1_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.GLuaHighlightTokenizer.IsGLuaFuncName(System.String)~System.Boolean" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonsAsync(System.String,WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.Int32)~System.Threading.Tasks.Task{WorkshopUtils.WorkshopAddon[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~F:WorkshopUtils.UI.GLuaHighlighter.GLuaHighlightTokenizer.Fns" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.GMAParserForm.Button1_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.GMAParserForm.ParseData(System.Byte[])" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetAddonByIDAsync(System.Int32)~System.Threading.Tasks.Task{WorkshopUtils.WorkshopAddon}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.SteamworksWorkshopAPI.DownloadGMAAsync(System.UInt64,System.Int32)~System.Threading.Tasks.Task{System.Byte[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.WorkshopDLForm.Button1_ClickAsync(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.ChoiceForm.#ctor" )]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:GUtils.Forms.FolderSelectDialog.ShowDialog(System.IntPtr)~System.Boolean" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:GUtils.Forms.Reflector.CallAs2(System.Type,System.Object,System.String,System.Object[])~System.Object" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:GUtils.Forms.Reflector.GetAs(System.Type,System.Object,System.String)~System.Object" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:GUtils.Forms.Reflector.GetEnum(System.String,System.String)~System.Object" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:GUtils.Forms.Reflector.GetType(System.String)~System.Type" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:GUtils.Forms.Reflector.New(System.String,System.Object[])~System.Object" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.GLuaCode.SetCode(System.String)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetAddonByIDAsync(System.Int32,System.String)~System.Threading.Tasks.Task{WorkshopUtils.WorkshopAddon}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.WebClientGETAsync(System.String,System.Collections.Specialized.NameValueCollection)~System.Threading.Tasks.Task{System.String}" )]
