// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific
// target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonIDs(WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.String[],System.Int32,System.Boolean)~System.Threading.Tasks.Task{System.Int32[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.DownloadAddonAsync(WorkshopUtils.WorkshopAddon,System.String)~System.Threading.Tasks.Task" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonIDsAsync(WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.String[],System.Int32)~System.Threading.Tasks.Task{System.Int32[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.DownloadAddonDataAsync(WorkshopUtils.WorkshopAddon)~System.Threading.Tasks.Task{System.Byte[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.DownloadAddonFileAsync(WorkshopUtils.WorkshopAddon,System.String)~System.Threading.Tasks.Task" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonsAsync(System.String,WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.Int32)~System.Threading.Tasks.Task{WorkshopUtils.WorkshopAddon[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0091:Use static method", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.ChoiceForm.Button1_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Style", "CC0061:Asynchronous method can be terminated with the 'Async' keyword.", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.ChoiceForm.Button1_Click(System.Object,System.EventArgs)" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.UI.GLuaHighlightTokenizer.IsGLuaFuncName(System.String)~System.Boolean" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~M:WorkshopUtils.WorkshopHTTPAPI.GetWorkshopAddonsAsync(System.String,WorkshopUtils.EPublishedFileQueryType,System.UInt32,System.Int32)~System.Threading.Tasks.Task{WorkshopUtils.WorkshopAddon[]}" )]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ( "Design", "CC0021:Use nameof", Justification = "<Pending>", Scope = "member", Target = "~F:WorkshopUtils.UI.GLuaHighlighter.GLuaHighlightTokenizer.Fns" )]
